<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Categories.aspx.cs" Inherits="Enews.Admin.Categories" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" AllowSorting="True" CssClass="table">
        <Columns>
            <asp:BoundField DataField="display" HeaderText="display" SortExpression="display" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [display] FROM [Categories]"></asp:SqlDataSource>
    <%--OnSelecting="SqlDataSource1_Selecting" --%>

    <div class="form-group">
        <asp:Label ID="Label1" runat="server" Text="Add new category"></asp:Label>
        <asp:TextBox ID="name" runat="server" CssClass="form-control" ></asp:TextBox>

        <asp:Button ID="Button1" runat="server" Text="Add Category" CssClass="btn btn-primary" OnClick="AddCategory"/>
    </div>

</asp:Content>
